In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
 import numpy as np

In [7]:
l=[1,2,3,4]

In [8]:
type(l)

list

In [10]:
np.array(l)

array([1, 2, 3, 4])

In [11]:
a=np.array(l)

In [12]:
a

array([1, 2, 3, 4])

In [13]:
type(a)

numpy.ndarray

In [14]:
a1=np.array([[1,2,3],[4,5,6]])

In [15]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a1.dtype

dtype('int32')

In [17]:
type(a)

numpy.ndarray

In [18]:
a2=np.array([[[1,2,3],[4,5,6]]])

In [19]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [21]:
a.ndim  # direction 1D

1

In [23]:
a1.ndim # 2D

2

In [25]:
a2.ndim #3D

3

In [27]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [28]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
a3.ndim

3

In [30]:
l=[1,2,3,4]

In [32]:
np.asanyarray(l) # onlu for 1D data

array([1, 2, 3, 4])

In [33]:
m=np.matrix(l) #2D data set

In [34]:
m

matrix([[1, 2, 3, 4]])

In [35]:
a

array([1, 2, 3, 4])

In [36]:
m

matrix([[1, 2, 3, 4]])

In [37]:
a

array([1, 2, 3, 4])

In [38]:
a[0]

1

In [39]:
a[0]=10

In [40]:
a

array([10,  2,  3,  4])

In [41]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a1[0]

array([1, 2, 3])

In [44]:
a1[1]

array([4, 5, 6])

In [45]:
a1[0][1]

2

In [46]:
a1[0][1]=40

In [47]:
a1

array([[ 1, 40,  3],
       [ 4,  5,  6]])

In [48]:
np.random.rand(2,3)# 2 rows 3 column

array([[0.82605059, 0.691887  , 0.33210534],
       [0.5090614 , 0.57938877, 0.51701212]])

In [51]:
np.random.rand(2,3,2)

array([[[0.46352718, 0.33575496],
        [0.16477603, 0.18729737],
        [0.32533756, 0.66134059]],

       [[0.33489876, 0.7442591 ],
        [0.89458309, 0.65611169],
        [0.01143342, 0.41461584]]])

In [52]:
np.random.rand(2,3,2,2)

array([[[[0.44354116, 0.81685597],
         [0.35375905, 0.80122275]],

        [[0.93625585, 0.76590804],
         [0.33015496, 0.15499038]],

        [[0.52414701, 0.40727606],
         [0.04806263, 0.81468087]]],


       [[[0.03227432, 0.732011  ],
         [0.9989801 , 0.0338306 ]],

        [[0.72743773, 0.23355698],
         [0.39400142, 0.41045897]],

        [[0.39747629, 0.55358665],
         [0.84125071, 0.37426089]]]])

In [53]:
np.random.rand(1,4,4)

array([[[0.34335427, 0.52932036, 0.69164403, 0.15294064],
        [0.24477666, 0.70622647, 0.68142034, 0.99953699],
        [0.54828838, 0.74139364, 0.05204384, 0.58990488],
        [0.39816284, 0.97948085, 0.92889741, 0.20320164]]])

In [54]:
np.random.rand(4,4,4)

array([[[0.01483755, 0.01114911, 0.71209209, 0.09038635],
        [0.11331157, 0.15885805, 0.68952454, 0.7156148 ],
        [0.27359752, 0.49999108, 0.96465662, 0.52144314],
        [0.66970179, 0.76662098, 0.50498489, 0.10077772]],

       [[0.54513063, 0.30837908, 0.42920407, 0.56732166],
        [0.85713948, 0.52747182, 0.31883016, 0.78325378],
        [0.71398172, 0.80116546, 0.27604844, 0.00138068],
        [0.46515239, 0.35275688, 0.01780415, 0.21154639]],

       [[0.46195847, 0.8447199 , 0.85130246, 0.65406773],
        [0.54922883, 0.85059557, 0.22960882, 0.41199994],
        [0.21076058, 0.44933736, 0.28992197, 0.195395  ],
        [0.31810134, 0.75070464, 0.2507951 , 0.80246903]],

       [[0.05562452, 0.04279379, 0.56643572, 0.38918077],
        [0.2307618 , 0.55144931, 0.12525665, 0.17528398],
        [0.36557063, 0.37302185, 0.65699635, 0.15960167],
        [0.32949341, 0.12882315, 0.83617755, 0.12013764]]])

In [57]:
np.random.randint(30,50,(2,4))

array([[33, 45, 34, 35],
       [34, 33, 41, 44]])

In [59]:
np.random.randint(30,50,(1,10))

array([[49, 47, 38, 44, 42, 30, 42, 34, 47, 48]])